// Active full-state coordinates for fixed-boundary corrections.
#ifndef CUMES_INCLUDE_CUMES_NUMERICS_CORRECTION_COORDINATES_HPP_
#define CUMES_INCLUDE_CUMES_NUMERICS_CORRECTION_COORDINATES_HPP_

#include "cumes/config/device_params.hpp"

#include <cuda_runtime.h>

namespace cumes {
namespace correction_detail {

// The unknown q has the same normalized, m=1-mixed coordinates as production
// preconditioned forces and velocities. Axis dependencies are regenerated by
// EquilibriumOperator before synthesis, so they are not independent unknowns.
__host__ __device__ inline bool active(int component,
                                       int m,
                                       int n,
                                       int j,
                                       int ns,
                                       bool fix_m1) {
    if (component == 2) return m > 0 && j > 0;
    if (component == 5) return n > 0 && j > 0;
    if (j == ns - 1 || (j == 0 && m > 0)) return false;
    if (component == 0) return true;
    if (component == 1) return m > 0;
    if (component == 3) return m > 0 && n > 0;
    return n > 0 && !(m == 1 && fix_m1);
}

}  // namespace correction_detail

// All pointers address contiguous [Rcc,Zsc,Lsc,Rss,Zcs,Lcs][mode][surface]
// slabs. Input/output aliasing is supported. This helper owns no buffers.
template <class T>
class CorrectionCoordinates {
   public:
    using val_type = T;

    CorrectionCoordinates(const DeviceParams<T>& p, bool fix_m1)
        : ns_(p.ns), mnmax_(p.mnmax), ntor_(p.ntor), fix_m1_(fix_m1) {}

    int size() const { return 6 * ns_ * mnmax_; }
    void set_fix_m1(bool fix_m1) { fix_m1_ = fix_m1; }

    void enqueue_pack(const T* d_residual, T* d_q, cudaStream_t stream) const;
    void enqueue_physical(const T* d_q,
                          T* d_physical,
                          cudaStream_t stream) const;

    // Effective scale is scale * *d_scale when the optional device scalar is
    // present, allowing norm-scaled finite differences without a host fence.
    void enqueue_trial(const T* d_base,
                       const T* d_q,
                       T* d_trial,
                       T scale,
                       cudaStream_t stream,
                       const T* d_scale = nullptr) const;

   private:
    int ns_, mnmax_, ntor_;
    bool fix_m1_;
};

}  // namespace cumes
#endif  // CUMES_INCLUDE_CUMES_NUMERICS_CORRECTION_COORDINATES_HPP_
