// input_w7x.h -- W7-X fixed-boundary input parameters.
// GENERATED by scripts/gen_w7x_header.py from w7x.json -- do not edit by hand.
#pragma once
#include "input.h"

namespace cumes_w7x {

// Scalar parameters.
constexpr int kmpol = 12;
constexpr int kntor = 12;
constexpr int knfp = 5;
constexpr int kntheta = 0;
constexpr int knzeta = 36;
constexpr int kns = 99;
constexpr int kmax_iter = 5000;
constexpr double kftol = 1e-12;
constexpr double kdelt = 1.0;
constexpr int kncurr = 1;
constexpr double kphiedge = -1.74;
constexpr double kpres_scale = 1.0;
constexpr double kadiabatic_index = 0.0;
constexpr double kspres_ped = 1.0;
constexpr double kbloat = 1.0;
constexpr double kcurtor = 5000.0;
constexpr double ktcon0 = 1.0;

// am: power-series coefficients.
constexpr int kamN = 2;
constexpr double kAm[2] = {166000.0, -166000.0};

// ac: power-series coefficients.
constexpr int kacN = 2;
constexpr double kAc[2] = {0.0, 1.0};

// ai: power-series coefficients.
constexpr int kaiN = 0;
constexpr double kAi[1] = {};

// aphi: power-series coefficients.
constexpr int kaphiN = 1;
constexpr double kAphi[1] = {1.0};

// Magnetic axis Fourier coefficients.
constexpr int kRaxisN = 13;
constexpr double kRaxisC[13] = {5.6343, 0.35209, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
constexpr double kZaxisS[13] = {0.0, -0.29578, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};

// rbc: raw boundary coefficients (n can be negative;
// folded into rbcc/rbss/zbsc/zbcs by initInputParams).
struct kRbcEntry { int m; int n; double value; };
constexpr int kRbcN = 85;
constexpr kRbcEntry kRbc[85] = {
  {0, 0, 5.5586},
  {0, 1, 0.26447},
  {0, 2, 0.0016949},
  {0, 3, -0.00094726},
  {0, 4, -0.0017618},
  {0, 5, 4.5981e-05},
  {0, 6, -0.00023437},
  {1, -6, 0.00058671},
  {1, -5, -0.0020214},
  {1, -4, -0.0032499},
  {1, -3, -0.0048626},
  {1, -2, 0.0099524},
  {1, -1, 0.033555},
  {1, 0, 0.49093},
  {1, 1, -0.25107},
  {1, 2, 0.0051767},
  {1, 3, 0.0048235},
  {1, 4, 0.00032065},
  {1, 5, 0.0001959},
  {1, 6, -0.0013768},
  {2, -6, 0.00050917},
  {2, -5, -0.00066977},
  {2, -4, -0.00067572},
  {2, -3, -0.0014368},
  {2, -2, 0.0020763},
  {2, -1, 0.014863},
  {2, 0, 0.038447},
  {2, 1, 0.039485},
  {2, 2, 0.063998},
  {2, 3, -0.0079348},
  {2, 4, 0.0026108},
  {2, 5, 0.0020567},
  {2, 6, 0.00054194},
  {3, -6, -0.0002123},
  {3, -5, 4.3695e-05},
  {3, -4, 0.00033644},
  {3, -3, 0.00064011},
  {3, -2, 0.0014828},
  {3, -1, 0.001668},
  {3, 0, -0.007879},
  {3, 1, -0.016151},
  {3, 2, -0.017821},
  {3, 3, -0.010231},
  {3, 4, 0.0020548},
  {3, 5, -0.0014357},
  {3, 6, -0.0006283},
  {4, -6, 0.00016361},
  {4, -5, -0.00016965},
  {4, -4, 0.00016596},
  {4, -3, 1.9015e-05},
  {4, -2, -0.00016802},
  {4, -1, -0.0018659},
  {4, 0, 0.003313},
  {4, 1, -0.0010438},
  {4, 2, 0.0092226},
  {4, 3, 0.00077604},
  {4, 4, 5.9064e-05},
  {4, 5, -5.2259e-05},
  {4, 6, 0.00030372},
  {5, -6, -9.7626e-05},
  {5, -5, -2.1519e-05},
  {5, -4, 4.0222e-05},
  {5, -3, -0.00029516},
  {5, -2, -0.00026001},
  {5, -1, 0.001071},
  {5, 0, 0.00079054},
  {5, 1, 0.0043576},
  {5, 2, -0.00089611},
  {5, 3, -0.00068915},
  {5, 4, 0.0016336},
  {5, 5, -0.00013732},
  {5, 6, 6.2276e-05},
  {6, -6, 4.932e-05},
  {6, -5, -0.00010468},
  {6, -4, 3.3192e-05},
  {6, -3, 0.00017365},
  {6, -2, 0.00038511},
  {6, -1, 0.00010762},
  {6, 0, 2.6971e-05},
  {6, 1, -0.003413},
  {6, 2, -0.0016615},
  {6, 3, -0.0010591},
  {6, 4, -0.00053034},
  {6, 5, -0.00065265},
  {6, 6, 9.7208e-05},
};

// zbs: raw boundary coefficients (n can be negative;
// folded into rbcc/rbss/zbsc/zbcs by initInputParams).
struct kZbsEntry { int m; int n; double value; };
constexpr int kZbsN = 84;
constexpr kZbsEntry kZbs[84] = {
  {0, 1, -0.23754},
  {0, 2, -0.0068221},
  {0, 3, 0.0031833},
  {0, 4, 0.0017251},
  {0, 5, 5.7592e-05},
  {0, 6, 0.0002643},
  {1, -6, 0.0013323},
  {1, -5, -0.0016138},
  {1, -4, -0.0042108},
  {1, -3, -0.0070096},
  {1, -2, 0.0096053},
  {1, -1, 0.036669},
  {1, 0, 0.61965},
  {1, 1, 0.17897},
  {1, 2, 0.0011535},
  {1, 3, 0.011208},
  {1, 4, 0.0042871},
  {1, 5, 0.0022236},
  {1, 6, -0.00031109},
  {2, -6, -0.00085478},
  {2, -5, 0.00038773},
  {2, -4, -0.0004941},
  {2, -3, 0.00014908},
  {2, -2, 0.0013789},
  {2, -1, 0.011065},
  {2, 0, -0.0089934},
  {2, 1, 0.023219},
  {2, 2, -0.055638},
  {2, 3, 0.010888},
  {2, 4, -0.00054241},
  {2, 5, -0.0010494},
  {2, 6, -6.6246e-05},
  {3, -6, 0.0001434},
  {3, -5, -6.3872e-06},
  {3, -4, -0.0001558},
  {3, -3, 0.00017715},
  {3, -2, 0.00039966},
  {3, -1, -0.0021165},
  {3, 0, -0.00042775},
  {3, 1, 0.00065673},
  {3, 2, 0.0075688},
  {3, 3, 0.0094628},
  {3, 4, -0.0025063},
  {3, 5, 0.00078944},
  {3, 6, 0.00037802},
  {4, -6, -0.00010181},
  {4, -5, 0.00012157},
  {4, -4, 4.6167e-05},
  {4, -3, -0.00024091},
  {4, -2, -0.00014719},
  {4, -1, -0.00041381},
  {4, 0, 0.00043528},
  {4, 1, 0.0016804},
  {4, 2, 0.0072835},
  {4, 3, -0.0060814},
  {4, 4, 1.6546e-05},
  {4, 5, 0.0009278},
  {4, 6, -0.00026709},
  {5, -6, -7.3965e-05},
  {5, -5, 0.00013889},
  {5, -4, -0.00020578},
  {5, -3, 0.00012722},
  {5, -2, 0.00021614},
  {5, -1, 0.0010369},
  {5, 0, 0.0015842},
  {5, 1, -0.0038666},
  {5, 2, -0.0024331},
  {5, 3, 0.00065004},
  {5, 4, 0.0005165},
  {5, 5, -0.00033282},
  {5, 6, -0.00019109},
  {6, -6, 1.7171e-06},
  {6, -5, -5.2834e-05},
  {6, -4, 7.6033e-05},
  {6, -3, 0.00011611},
  {6, -2, 5.5193e-05},
  {6, -1, -1.5852e-05},
  {6, 0, -0.00058329},
  {6, 1, -0.00023786},
  {6, 2, -0.00042717},
  {6, 3, -0.00081209},
  {6, 4, -0.00040144},
  {6, 5, 0.00024175},
  {6, 6, -0.0001894},
};

}  // namespace cumes_w7x

// Fill an InputParams from the W7-X constants above.
inline void setW7xParams(InputParams& p) {
    using namespace cumes_w7x;
    p.mpol = kmpol; p.ntor = kntor; p.nfp = knfp;
    p.ntheta = kntheta; p.nzeta = knzeta; p.ns = kns;
    p.ncurr = kncurr;
    p.delt = kdelt; p.ftol = kftol; p.max_iter = kmax_iter;
    p.phiedge = kphiedge;
    p.pres_scale = kpres_scale; p.adiabatic_index = kadiabatic_index;
    p.spres_ped = kspres_ped; p.bloat = kbloat;
    p.curtor = kcurtor; p.tcon0 = ktcon0;
    p.am_n = kamN; for (int i = 0; i < kamN; ++i) p.am[i] = kAm[i];
    p.ac_n = kacN; for (int i = 0; i < kacN; ++i) p.ac[i] = kAc[i];
    p.ai_n = kaiN; for (int i = 0; i < kaiN; ++i) p.ai[i] = kAi[i];
    p.aphi_n = kaphiN; for (int i = 0; i < kaphiN; ++i) p.aphi[i] = kAphi[i];
    p.raxis_n = kRaxisN;
    for (int i = 0; i < kRaxisN; ++i) { p.raxis_c[i] = kRaxisC[i]; p.zaxis_s[i] = kZaxisS[i]; }
    p.rbc_n = kRbcN; for (int i = 0; i < kRbcN; ++i) p.rbc[i] = {kRbc[i].m, kRbc[i].n, kRbc[i].value};
    p.zbs_n = kZbsN; for (int i = 0; i < kZbsN; ++i) p.zbs[i] = {kZbs[i].m, kZbs[i].n, kZbs[i].value};
}
