foreach(extension IN ITEMS html js wasm)
  set(path "${ARTIFACT_BASE}.${extension}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "missing WebGPU artifact: ${path}")
  endif()
  file(SIZE "${path}" size)
  if(size EQUAL 0)
    message(FATAL_ERROR "empty WebGPU artifact: ${path}")
  endif()
endforeach()
